pulls:
  labels:
    - label:
      name: "needs review" # This is the label we want to set, so it is implicitly checked.
      add:
        - when: # or, this - In each when: all properties uses AND, and whens uses OR.
          notLabeled:
            - on hold
        - when: # or, this
          notLabeled:
            - waiting for author response
        - when: # or, this
          notLabeled:
            - waiting for code fix
      remove:
        - when: # or, this
          canBeMerged: true
        - when:
          reviewApproved: true
    - label:
      name: "waiting for code fix"
      add:
        - when:
          reviewApproved: false
      remove:
        - when:
          onPush: true
    - label:
      name: "ready for merge"
      add:
        - when: # or, this
          canBeMerged: true # and, this
          notLabeled: # and, this
            - on hold
            - waiting for author response
            - waiting for code fix
          reviewApproved: true # This could check that only be true if there are no pushes after last approval.
      remove:
        - when:
          onPush: true
