# Status can be set to either: success, failure, pending or error

- when:
    statuses:
      cla-bot: failure

    label: waiting for CLA pass

    # Optional comment written when setting the label
    commentWhenSettingLabel: >
      Waiting for...
      When signed the..

    # Optional, removes all of these labels when setting 'label:'.
    removeLabels:
      - needs review
      - waiting for code fix

- when:
    statuses:
      continuous-integration/travis-ci/pr: failure
      cla-bot: success
      wip: success

    label: waiting for code fix

    commentWhenSettingLabel: >
      CI pipeline failed...

    removeLabels:
      - needs review
      - waiting for CLA pass


- when:
    statuses:
      continuous-integration/travis-ci/pr: success
      cla-bot: success
      wip: success

    label: needs review

    removeLabels:
      - waiting for code fix
      - waiting for CLA pass
